export enum NotificationType {
  COMMENT = 'COMMENT',
  FOLLOW_DEMAND = 'FOLLOW_DEMAND',
  FOLLOW_REFUSED = 'FOLLOW_REFUSED',
  FOLLOW_ACCEPTED = 'FOLLOW_ACCEPTED',
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
}
